@host = http://localhost:5113

POST {{host}}/api/transactions
Content-Type: application/json

{
  "ProductID": 1,
  "TransactionTypeID": 1,
  "Quantity": 50,
  "ReferenceDocument": "FAC-0001",
  "Notes": "Carga inicial de stock"
}

### Obtener el inventario completo
GET {{host}}/api/stocks

### Obtener el stock de un producto específico
GET {{host}}/api/stocks/1